FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386
RUN apt update
RUN apt -y install curl gnupg tzdata
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN curl -s https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
RUN echo deb https://dl.winehq.org/wine-builds/ubuntu/ focal main | tee /etc/apt/sources.list.d/wine.list
RUN apt update
RUN apt -y install --install-recommends winehq-stable
